config: &default
  server:
    port: 8080
  repo:
    eventsFile:
      dir: "./tmp/pages/events"
    git:
      url: "https://github.com/yotzapon/apispec.git"
      remoteName: "origin"   # "HEAD"
      destination: "./tmp/"
      auth:
        userName: "token"

  
local: 
  <<: *default  

dev:
  <<: *default  