config: &default
  server:
    port: 3000
  repo:
    eventsFile:
      dir: "./tmp/pages/events"
    git:
      url: "https://github.com/yotzapon/apispec.git"
      remoteName: "origin"   # "HEAD"
      destination: "./tmp/"
      auth:
        userName: "token"
        passWord: "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"

  
local: 
  <<: *default  

dev:
  <<: *default  